const field = (id, label, type, extra = {}) => ({
  id,
  label,
  type,
  required: Boolean(extra.required),
  placeholder: extra.placeholder || "",
  helpText: extra.helpText || "",
  options: extra.options || [],
  validation: extra.validation || { min: null, max: null, pattern: null },
  visibility: extra.visibility || "public",
  appliesTo: extra.appliesTo || "listing",
  sortOrder: extra.sortOrder ?? 0,
});

const CATEGORY_SEED = [
  {
    slug: "hotel",
    name: "Hotel",
    group: "Accommodation",
    sortOrder: 10,
    supportsOptions: true,
    defaults: { suggestedCancelWindowHours: 24 },
    listingFieldSchema: [
      field("checkInTime", "Check-in time", "time", { required: true, sortOrder: 1 }),
      field("checkOutTime", "Check-out time", "time", { required: true, sortOrder: 2 }),
      field("starRating", "Star rating", "select", {
        options: ["unrated", "1-star", "2-star", "3-star", "4-star", "5-star"],
        sortOrder: 3,
      }),
      field("amenities", "Amenities", "textarea", { helpText: "Comma-separated amenities", sortOrder: 4 }),
    ],
    optionFieldSchema: [
      field("maxGuests", "Max guests", "number", { required: true, appliesTo: "option", sortOrder: 1 }),
      field("beds", "Beds", "text", { appliesTo: "option", sortOrder: 2 }),
      field("breakfastIncluded", "Breakfast included", "boolean", { appliesTo: "option", sortOrder: 3 }),
    ],
    bookingFieldSchema: [
      field("checkIn", "Check-in date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("checkOut", "Check-out date", "date", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("guests", "Number of guests", "number", { required: true, appliesTo: "booking", sortOrder: 3 }),
      field("specialRequests", "Special requests", "textarea", { appliesTo: "booking", sortOrder: 4 }),
    ],
  },
  {
    slug: "apartment",
    name: "Apartment",
    group: "Accommodation",
    sortOrder: 20,
    supportsOptions: true,
    listingFieldSchema: [
      field("amenities", "Amenities", "textarea", { sortOrder: 1 }),
      field("maxGuests", "Max guests", "number", { required: true, sortOrder: 2 }),
    ],
    optionFieldSchema: [
      field("bedrooms", "Bedrooms", "number", { appliesTo: "option", sortOrder: 1 }),
    ],
    bookingFieldSchema: [
      field("checkIn", "Check-in date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("checkOut", "Check-out date", "date", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("guests", "Guests", "number", { required: true, appliesTo: "booking", sortOrder: 3 }),
    ],
  },
  {
    slug: "homestay",
    name: "Homestay",
    group: "Accommodation",
    sortOrder: 30,
    supportsOptions: true,
    listingFieldSchema: [field("amenities", "Amenities", "textarea", { sortOrder: 1 })],
    optionFieldSchema: [field("maxGuests", "Max guests", "number", { appliesTo: "option", sortOrder: 1 })],
    bookingFieldSchema: [
      field("checkIn", "Check-in date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("checkOut", "Check-out date", "date", { required: true, appliesTo: "booking", sortOrder: 2 }),
    ],
  },
  {
    slug: "car-rental",
    name: "Car Rental",
    group: "Transport Services",
    sortOrder: 40,
    supportsOptions: true,
    defaults: { suggestedCancelWindowHours: 6 },
    listingFieldSchema: [
      field("vehicleClass", "Vehicle class", "select", {
        required: true,
        options: ["Economy", "Compact", "SUV", "Van", "Luxury"],
        sortOrder: 1,
      }),
      field("transmission", "Transmission", "select", {
        required: true,
        options: ["Automatic", "Manual"],
        sortOrder: 2,
      }),
      field("withDriver", "With driver?", "boolean", { sortOrder: 3 }),
      field("fuelPolicy", "Fuel policy", "select", {
        options: ["Full-to-full", "Same-to-same", "Prepaid"],
        sortOrder: 4,
      }),
      field("insuranceIncluded", "Insurance included?", "boolean", { sortOrder: 5 }),
      field("depositNote", "Deposit note", "textarea", { visibility: "public", sortOrder: 6 }),
    ],
    optionFieldSchema: [
      field("seats", "Seats", "number", { required: true, appliesTo: "option", sortOrder: 1 }),
      field("luggage", "Luggage capacity", "text", { appliesTo: "option", sortOrder: 2 }),
      field("ac", "Air conditioning", "boolean", { appliesTo: "option", sortOrder: 3 }),
    ],
    bookingFieldSchema: [
      field("pickupLocation", "Pickup location", "text", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("returnLocation", "Return location", "text", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("pickupDateTime", "Pickup date/time", "datetime-local", { required: true, appliesTo: "booking", sortOrder: 3 }),
      field("returnDateTime", "Return date/time", "datetime-local", { required: true, appliesTo: "booking", sortOrder: 4 }),
      field("driverLicenseNumber", "Driver license number", "text", {
        required: true,
        appliesTo: "booking",
        visibility: "after_payment",
        sortOrder: 5,
      }),
      field("numberOfDrivers", "Number of drivers", "number", { required: true, appliesTo: "booking", sortOrder: 6 }),
    ],
  },
  {
    slug: "taxi",
    name: "Taxi Service",
    group: "Transport Services",
    sortOrder: 50,
    supportsOptions: true,
    listingFieldSchema: [field("vehicleType", "Vehicle type", "text", { required: true, sortOrder: 1 })],
    optionFieldSchema: [field("seats", "Seats", "number", { appliesTo: "option", sortOrder: 1 })],
    bookingFieldSchema: [
      field("pickupLocation", "Pickup location", "text", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("dropoffLocation", "Drop-off location", "text", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("pickupDateTime", "Pickup date/time", "datetime-local", { required: true, appliesTo: "booking", sortOrder: 3 }),
    ],
  },
  {
    slug: "motorbike",
    name: "Motorbike Rental",
    group: "Transport Services",
    sortOrder: 60,
    supportsOptions: true,
    listingFieldSchema: [field("helmetIncluded", "Helmet included", "boolean", { sortOrder: 1 })],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("pickupDateTime", "Pickup date/time", "datetime-local", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("returnDateTime", "Return date/time", "datetime-local", { required: true, appliesTo: "booking", sortOrder: 2 }),
    ],
  },
  {
    slug: "tour",
    name: "Tour / Experience",
    group: "Destination Experiences",
    sortOrder: 70,
    supportsOptions: true,
    listingFieldSchema: [
      field("duration", "Duration", "text", { required: true, sortOrder: 1 }),
      field("difficulty", "Difficulty", "select", {
        options: ["Easy", "Moderate", "Challenging"],
        sortOrder: 2,
      }),
      field("meetingPoint", "Meeting point", "text", { required: true, sortOrder: 3 }),
    ],
    optionFieldSchema: [
      field("packageType", "Package type", "select", {
        options: ["Adult", "Child", "Family"],
        appliesTo: "option",
        sortOrder: 1,
      }),
    ],
    bookingFieldSchema: [
      field("preferredDate", "Preferred date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("participants", "Participants", "number", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("language", "Preferred language", "text", { appliesTo: "booking", sortOrder: 3 }),
    ],
  },
  {
    slug: "activity-operator",
    name: "Activity Operator",
    group: "Destination Experiences",
    sortOrder: 80,
    supportsOptions: true,
    listingFieldSchema: [field("duration", "Duration", "text", { sortOrder: 1 })],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("preferredDate", "Preferred date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("participants", "Participants", "number", { required: true, appliesTo: "booking", sortOrder: 2 }),
    ],
  },
  {
    slug: "conference",
    name: "Meeting / Conference Room",
    group: "Venue Rentals",
    sortOrder: 90,
    supportsOptions: true,
    listingFieldSchema: [
      field("maxCapacity", "Max capacity", "number", { required: true, sortOrder: 1 }),
      field("amenities", "Amenities", "textarea", { sortOrder: 2 }),
      field("cateringAvailable", "Catering available?", "boolean", { sortOrder: 3 }),
    ],
    optionFieldSchema: [
      field("packageName", "Package name", "text", { appliesTo: "option", sortOrder: 1 }),
    ],
    bookingFieldSchema: [
      field("eventDate", "Event date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("startTime", "Start time", "time", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("endTime", "End time", "time", { required: true, appliesTo: "booking", sortOrder: 3 }),
      field("attendees", "Attendees", "number", { required: true, appliesTo: "booking", sortOrder: 4 }),
      field("setupStyle", "Setup style", "text", { appliesTo: "booking", sortOrder: 5 }),
      field("avNeeds", "AV needs", "textarea", { appliesTo: "booking", sortOrder: 6 }),
    ],
  },
  {
    slug: "event-hall",
    name: "Event Hall",
    group: "Venue Rentals",
    sortOrder: 100,
    supportsOptions: true,
    listingFieldSchema: [field("maxCapacity", "Max capacity", "number", { required: true, sortOrder: 1 })],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("eventDate", "Event date", "date", { required: true, appliesTo: "booking", sortOrder: 1 }),
      field("attendees", "Attendees", "number", { required: true, appliesTo: "booking", sortOrder: 2 }),
    ],
  },
  {
    slug: "restaurant",
    name: "Restaurant",
    group: "Food & Drink",
    sortOrder: 110,
    supportsOptions: false,
    listingFieldSchema: [
      field("cuisine", "Cuisine", "text", { required: true, sortOrder: 1 }),
      field("dressCode", "Dress code", "text", { sortOrder: 2 }),
      field("averagePrice", "Average price (RWF)", "number", { sortOrder: 3 }),
    ],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("reservationDateTime", "Reservation date/time", "datetime-local", {
        required: true,
        appliesTo: "booking",
        sortOrder: 1,
      }),
      field("partySize", "Party size", "number", { required: true, appliesTo: "booking", sortOrder: 2 }),
      field("allergies", "Allergies", "textarea", { appliesTo: "booking", sortOrder: 3 }),
    ],
  },
  {
    slug: "cafe",
    name: "Cafe",
    group: "Food & Drink",
    sortOrder: 120,
    supportsOptions: false,
    listingFieldSchema: [field("cuisine", "Cuisine / specialty", "text", { sortOrder: 1 })],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("reservationDateTime", "Reservation date/time", "datetime-local", {
        required: true,
        appliesTo: "booking",
        sortOrder: 1,
      }),
      field("partySize", "Party size", "number", { required: true, appliesTo: "booking", sortOrder: 2 }),
    ],
  },
  {
    slug: "bar",
    name: "Bar",
    group: "Food & Drink",
    sortOrder: 130,
    supportsOptions: false,
    listingFieldSchema: [field("atmosphere", "Atmosphere", "text", { sortOrder: 1 })],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("reservationDateTime", "Reservation date/time", "datetime-local", {
        required: true,
        appliesTo: "booking",
        sortOrder: 1,
      }),
      field("partySize", "Party size", "number", { required: true, appliesTo: "booking", sortOrder: 2 }),
    ],
  },
  {
    slug: "other",
    name: "Other Service",
    group: "Other",
    sortOrder: 999,
    supportsOptions: true,
    listingFieldSchema: [],
    optionFieldSchema: [],
    bookingFieldSchema: [
      field("preferredDate", "Preferred date", "date", { appliesTo: "booking", sortOrder: 1 }),
      field("notes", "Notes", "textarea", { appliesTo: "booking", sortOrder: 2 }),
    ],
  },
];

module.exports = { CATEGORY_SEED };
